### ISSUE TITLE
Question: any way to include source location where an anomaly is created?

### ISSUE THREAD

**Issue by stevebuik** [otto-de/nom#6]
I've come to love this style of error handling and use it extensively.

In monitoring systems, we now see anomalies but unlike an exception/stack trace it can be difficult to back-track to find location where the anomaly was created.

Are there any techniques (other than unique kinds) or feature ideas that might help with this?

**Comment by svantevonerichsen6906** [comment]
I understand the issue, and I think there is no general solution to this.  One thing that I always found helpful is to save as much contextual data in the anomaly payload as sensible (this is similar to ex-info).  If you have several semantic layers, it might sometimes make sense to wrap lower-level anomalies in higher-level ones, adding contextual data at each level.  Other than that, I often use namespaced keywords as kinds, relying on auto-namespacing with `::`.

**Comment by stevebuik** [comment]
Yeah, I thought this was likely the problem so kinds and context are the best option.

thanks for the update.
